#!/usr/bin/env python3
"""Generate COMPLETE country borders for the SentinelAI connection map.

Run once, on a machine with a working internet connection:

    python3 scripts/build_borders.py

It downloads Natural Earth's 110m country boundaries (~107 KB) and writes
frontend/src/components/world-borders.js with every country's border lines
worldwide. Then just refresh the dashboard — the Connection Geography map will
show borders for all continents.

Stdlib only (no pip install needed).
"""
from __future__ import annotations

import json
import math
import os
import urllib.request

URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "frontend", "src",
                   "components", "world-borders.js")


def rdp(pts, eps):
    """Ramer–Douglas–Peucker simplification."""
    if len(pts) < 3:
        return pts

    def d(p, a, b):
        (x, y), (x1, y1), (x2, y2) = p, a, b
        dx, dy = x2 - x1, y2 - y1
        if dx == dy == 0:
            return math.hypot(x - x1, y - y1)
        t = max(0, min(1, ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)))
        return math.hypot(x - (x1 + t * dx), y - (y1 + t * dy))

    dmax, idx = 0, 0
    for k in range(1, len(pts) - 1):
        dd = d(pts[k], pts[0], pts[-1])
        if dd > dmax:
            dmax, idx = dd, k
    if dmax > eps:
        return rdp(pts[:idx + 1], eps)[:-1] + rdp(pts[idx:], eps)
    return [pts[0], pts[-1]]


def split_antimeridian(line):
    """Split a polyline where it jumps across the +/-180 date line."""
    out, cur = [], [line[0]]
    for a, b in zip(line, line[1:]):
        if abs(b[0] - a[0]) > 180:
            out.append(cur)
            cur = [b]
        else:
            cur.append(b)
    out.append(cur)
    return out


def main():
    print("Downloading country boundaries ...")
    raw = urllib.request.urlopen(URL, timeout=30).read()
    topo = json.loads(raw)

    sx, sy = topo["transform"]["scale"]
    tx, ty = topo["transform"]["translate"]

    # Decode (dequantize) every arc to absolute lon/lat coordinates.
    arcs = []
    for arc in topo["arcs"]:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)

    # Collect the set of arcs used by all country geometries (deduped, so a
    # shared border between two countries is drawn once).
    used = set()

    def collect(geom):
        t = geom["type"]
        if t == "Polygon":
            for ring in geom["arcs"]:
                for i in ring:
                    used.add(i if i >= 0 else ~i)
        elif t == "MultiPolygon":
            for poly in geom["arcs"]:
                for ring in poly:
                    for i in ring:
                        used.add(i if i >= 0 else ~i)

    obj = topo["objects"]["countries"]
    geoms = obj["geometries"] if obj["type"] == "GeometryCollection" else [obj]
    for g in geoms:
        collect(g)

    # Turn each used arc into a simplified, antimeridian-safe polyline.
    lines = []
    for i in sorted(used):
        for seg in split_antimeridian(arcs[i]):
            if len(seg) < 2:
                continue
            s = rdp(seg, 0.3) if len(seg) > 2 else seg
            lines.append([[round(x, 2), round(y, 2)] for x, y in s])

    out = ["// Country border lines — Natural Earth 110m (full world).",
           "// Generated by scripts/build_borders.py. [lon,lat] polylines.",
           "export const BORDERS = ["]
    for line in lines:
        out.append("  [" + ",".join(f"[{x},{y}]" for x, y in line) + "],")
    out.append("];")
    with open(os.path.abspath(OUT), "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"Wrote {os.path.abspath(OUT)}")
    print(f"  {len(lines)} border lines covering every country. Refresh the dashboard.")


if __name__ == "__main__":
    main()
